#pragma once

#include "NativeGameplayTags.h"

namespace RBAI::Tags
{
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Idle);
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Flee);
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Pursue);
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Attack);
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Investigate);
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Feed);
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Rest);
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Guard);
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Flank);
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_TakeCover);

    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Signal_Health);
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Signal_Threat);
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Signal_Distance);
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Signal_Sight);
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Signal_Hearing);
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Signal_Hunger);
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Signal_Fatigue);
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Signal_TerritoryDistance);
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Signal_PackSupport);

    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Threatened);
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_InCombat);
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Creature);
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Boss);
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Context_Self);
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Context_Hostile);
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Context_Friendly);
    RBAICORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Context_Perceived);
}
