"""Build the mission review from inspected local evidence; never creates game art."""
from pathlib import Path
import argparse,json,html
R=Path(__file__).resolve().parents[2]
p=argparse.ArgumentParser();p.add_argument('--evidence-root',type=Path,required=True);a=p.parse_args();E=a.evidence_root.resolve();assert E.is_relative_to(R/'Evidence')
review=json.loads((E/'visual-inspection.json').read_text());cards=[]
for row in review['captures']:
 image=E/row['path'];assert image.is_file()
 cards.append('<article><a href="'+html.escape(row['path'],quote=True)+'"><img loading="lazy" src="'+html.escape(row['path'],quote=True)+'"></a><h3>'+html.escape(image.stem.replace('_',' '))+'</h3><p>'+html.escape(row['review'])+'</p><small>'+html.escape(row.get('art_limit',''))+'</small></article>')
body='<!doctype html><html lang="en"><meta charset="utf-8"><title>Soul — Six-faction state and Viking infantry proof</title><style>body{background:#171a1e;color:#e7e6df;font:16px/1.55 system-ui;max-width:1500px;margin:auto;padding:32px}h1{font-size:32px}h2{margin-top:40px}a{color:#b3d6e2}header{max-width:1000px}section{display:grid;grid-template-columns:repeat(auto-fit,minmax(430px,1fr));gap:22px}article{background:#24292e;padding:15px;border-radius:6px}img{width:100%;height:auto}small{color:#bfc6c9}.status{border-left:4px solid #87b2a5;padding:12px 20px;background:#24292e}</style><header><h1>Six canonical factions. One new exact infantry roster.</h1><p class="status">Opt-in qualification profiles. AI OFF. The 3.5 km world and retained reference remain unchanged. This is state/save and roster acceptance, not final map art or six-faction balance.</p><p>Six-faction ownership, six controlled legal moves, F5/F9, and separate-process restoration pass. Viking Ulf axe infantry uses owned mesh, compatible animations, actual hand-attached weapon and existing RBCombat. Ordinary combat evidence is separate from paused close-pose inspection.</p><p>Only Human attackers versus Dwarf, Orc or Viking defenders are admitted. Nature/Dark combat and the other ordered pairs reject explicitly. Directed approaches remain 20 explicit / 82 unset.</p><p><a href="HANDOFF.md">Handoff</a> · <a href="six-faction-readiness.md">Readiness</a> · <a href="state-proof-cooked.json">Cooked state proof</a> · <a href="viking-victory-result.json">Natural victory</a> · <a href="viking-defeat-result.json">Natural defeat</a> · <a href="preservation-after.json">Preservation hashes</a></p><p>All functional captures use a bounded frame cap and the 85°C guard. No sustained performance pass is claimed. Existing terrain/material and Dwarf exterior art debt remain separate.</p></header><h2>Reviewed native captures</h2><section>'
(E/'visual-review.html').write_text(body+'\n'.join(cards)+'</section></html>',encoding='utf-8');print('REVIEW_WRITTEN',len(cards))
