"""Evidence-backed six-faction readiness; never activates AI or supplies invented approaches."""
from pathlib import Path
import json,argparse,hashlib,itertools
R=Path(__file__).resolve().parents[2]
p=argparse.ArgumentParser();p.add_argument('--evidence-root',type=Path,required=True);a=p.parse_args();E=a.evidence_root.resolve();assert E.is_relative_to(R/'Evidence')
state=json.loads((E/'state-proof-cooked.json').read_text());match=json.loads((E/'viking-victory-result.json').read_text());assert state['pass'] and match['pass']
prior=json.loads((R/'Evidence/CleanFoundationAdmission-20261008/six-faction-readiness.json').read_text())
units={'humans':'human_knight','dwarves':'dwarf_warrior','orcs':'orc_hammer_warrior','vikings':'viking_axe_warrior'}
coverage={'humans':'Previously qualified complete CastleTown authored city and Dragon Graveyard field variants. Unchanged this mission.','dwarves':'Previously qualified authored Dwarf Hold environment and inherited field matchup. Strategic exterior remains provisional.','orcs':'Qualified owned Orc Hammer infantry on Dragon Graveyard badlands field; no Orc authored-capital integration claimed.','vikings':'Exact axe infantry at canonical Snow Pass using existing Dragon Graveyard rocky pass field. Snow/boreal art and actual Viking capital remain unqualified.','nature':'No exact admitted combat roster/battle environment pairing. Approved Nature donors remain content candidates.','dark':'Owned evil regional environments exist; no exact admitted Dark combat roster pairing.'}
settlements={'humans':'Authored CastleTown visit/battle/state proof and deterministic strategic miniature previously qualified; unchanged.', 'dwarves':'Authored Hold/state proof qualified; campaign exterior PROVISIONAL; untouched.', 'vikings':'Harbor/capital canonical location exists; strategic settlement art provisional; no authored Viking capital proof.', 'orcs':'Campaign camp/ruins presentation provisional; no authored Orc capital proof.', 'nature':'Canonical Treehold and approved Forest_village donors; strategic presentation provisional; no deep authored proof.', 'dark':'Canonical fortress and owned regional donors; strategic fortress/causeway presentation provisional; no deep authored proof.'}
rows=[]
for old in prior['factions']:
 f=old['faction'];army=next(x for x in state['armies'] if x['faction']==f)
 rows.append({'faction':f,'capital_region':old['capital_region'],'secondary_region':old['secondary_region'],'starting_ownership_ready':True,'starting_possessions':old['canonical_starting_possessions'],'strategic_army_ready':True,'army_id':army['army_id'],'qualification_count':army['troops'],'army_visual':'Existing campaign marker/count plus exact faction inspection; final six-faction army miniature art not claimed.','exact_unit':units.get(f),'settlement_capital_status':settlements[f],'environment_role_authority':old['environment_role_authority'],'battlefield_coverage':coverage[f],'save_restore':'Cooked F5/F9 and separate process exact restore; adversarial atomic rejection and RBSave rollback pass.','ai_enabled':False,'ai_readiness':'OFF; no diplomacy, non-Human recruitment economy, balancing or autonomous scheduling implemented.','seven_unit_families_ready':False})
ids=[r['faction'] for r in rows];pairs=[]
for attacker,defender in itertools.permutations(ids,2):pairs.append({'attacker':attacker,'defender':defender,'admitted':attacker=='humans' and defender in {'dwarves','orcs','vikings'},'reason':'Exact tested ordered bridge pair' if attacker=='humans' and defender in {'dwarves','orcs','vikings'} else 'Explicit rejection; no reversed/generic roster substitution'})
g=json.loads((R/'Data/soul_world_overmap_v1_20260922.json').read_text());h=json.loads((R/'Data/soul_overmap_battle_handoff_v1_20260922.json').read_text());existing={(x['source_region'],x['destination_region']) for x in h['handoffs']}
approaches=[{'source':s,'destination':t,'entry_direction':next((x['strategic_route']['entry_direction'] for x in h['handoffs'] if x['source_region']==s and x['destination_region']==t),None)} for edge in g['edges'] for s,t in [(edge['a'],edge['b']),(edge['b'],edge['a'])]]
assert len(approaches)==102 and sum(x['entry_direction'] is not None for x in approaches)==20
out={'status':'OPT_IN_QUALIFICATION_STATE; NOT SIX_FACTION_GAMEPLAY_RELEASE','regions':36,'edges':51,'owned_start':12,'neutral_start':24,'factions':rows,'ordered_matchups':pairs,'admitted_ordered_pairs':sum(x['admitted'] for x in pairs),'unsupported_ordered_pairs':sum(not x['admitted'] for x in pairs),'approaches':approaches,'explicit_approaches':20,'unset_approaches':82,'new_exercised_connection':{'source':'mountain_shrine','destination':'viking_snow_pass','battlefield':'dragon_pass','entry_direction':None,'status':'Existing landform/feature-matched fallback exercised; no unverified directional staging recipe fabricated.'},'ai_enabled':False,'ready_for_controlled_six_faction_ai':False,'next_gates':['Define a bounded controlled-AI action/admission policy that explicitly handles unsupported encounters; no implicit resolution.','Qualify Nature/Dark exact rosters and additional ordered matchups before full military AI.','Approve starting forces, non-Human resources/recruitment and diplomacy separately.'],'evidence':['state-proof-cooked.json','viking-victory-result.json','native-regressions-final.json']}
(E/'six-faction-readiness.json').write_text(json.dumps(out,indent=2)+'\n')
lines=['# Six-faction readiness','', 'Canonical state and persistence are qualified in an isolated profile. AI remains OFF. Test forces are not balance approval.','','| Faction | Start / army / save | Exact infantry | Environment status |','|---|---|---|---|']
for x in rows:lines.append('| '+x['faction']+' | PASS / PASS / PASS | '+(x['exact_unit'] or 'UNSUPPORTED')+' | '+x['battlefield_coverage']+' |')
lines+=['','## Settlement / capital status','']
for x in rows:lines.append('- **'+x['faction']+'**: '+x['settlement_capital_status'])
lines+=['','Only Human attackers versus exact Dwarf, Orc or Viking defenders are admitted: **3 of 30 ordered cross-faction pairs**. All other pairs reject safely. This is not a complete faction roster or autonomous strategy layer.','','Directed approaches remain **20 explicit / 82 unset**. The exercised Shrine-to-Snow-Pass encounter uses the existing pass recipe fallback. No guessed directional recipe was added.','','Next: approve a narrow controlled-AI action policy and resolve unsupported battle admission before enabling military AI. Nature/Dark rosters, faction economies, recruitment and diplomacy remain separate work.']
(E/'six-faction-readiness.md').write_text('\n'.join(lines)+'\n');print('READINESS_WRITTEN')
