"""Compose local evidence only. Screenshots remain unchanged; no shipped art."""
from pathlib import Path
import json,html,os,hashlib
from PIL import Image,ImageDraw,ImageFont
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'Evidence/TerrainFoundation-20261007';LOCAL=OUT/'Local';LOCAL.mkdir(exist_ok=True)
CAP=LOCAL/'candidate-r3-captures';REF=ROOT/'Evidence/SettlementEnvironmentPlan-20261005/Local/retained-population-after-r7/User/Saved/Screenshots'
font=lambda n:ImageFont.truetype('C:/Windows/Fonts/segoeui.ttf',n)
views=[('whole_labels_minimized','Whole 3.5 km study — unqualified'),('ordinary_heartland','850 m regional view — not default zoom'),('human_capital_scale','Capital scale study — existing mesh unchanged'),('dwarf_mountains','Dwarf region — useful ridge/basin relief'),('northern_coast','Viking site — enclosed lake, NOT sea harbor'),('orc_eastern_terrain','Orc region — gullies, no mesa treatment'),('nature_terrain','Nature region — provisional sparse woodland'),('dark_southern_terrain','Dark region — no ash/corruption treatment'),('pass_study','Pass study — existing valley, traced road'),('ford_site_unresolved','River Ford — shoreline; crossing NOT solved'),('minor_settlement_scale','Minor settlement scale — static assembly'),('close_ground_road','Close surface/road — provisional material')]
sheet=Image.new('RGB',(1800,4*380),'#14202a');d=ImageDraw.Draw(sheet)
for i,(name,caption) in enumerate(views):
 x=(i%3)*600;y=(i//3)*380
 with Image.open(CAP/(name+'.png')) as im:sheet.paste(im.resize((600,338)),(x,y))
 d.text((x+10,y+344),caption,font=font(17),fill='white')
sheet.save(LOCAL/'candidate-contact-sheet.jpg',quality=92)
pairs=[('Retained 1.5 km / qualified reference',REF/'population-after-r5_retained_overview.png'),('3.5 km study / normalized framing',LOCAL/'matched-comparison/whole_same_normalized_framing.png'),('Retained capital / 320 m camera',REF/'population-after-r5_crownstead_ordinary.png'),('Candidate capital / same 320 m camera',LOCAL/'matched-comparison/capital_same_320m_camera.png')]
sheet=Image.new('RGB',(1920,1160),'#14202a');d=ImageDraw.Draw(sheet)
for i,(name,path) in enumerate(pairs):
 x=i%2*960;y=i//2*580
 with Image.open(path) as im:sheet.paste(im.resize((960,540)),(x,y+36))
 d.text((x+12,y+5),name,font=font(25),fill='white')
sheet.save(LOCAL/'scale-comparison.jpg',quality=94)
def uri(p):return html.escape(os.path.relpath(p,OUT).replace('\\','/'),quote=True)
def card(title,path,caption):return f'<figure><a href="{uri(path)}"><img loading="lazy" src="{uri(path)}" alt="{html.escape(title)}"></a><figcaption><b>{html.escape(title)}</b><br>{html.escape(caption)}</figcaption></figure>'
native=Path('D:/RefinedBadger/AssetLibraries/SoulTerrainPreview/Captures/landscapes_mountain_05_campaign.png')
r10=ROOT/'Evidence/CampaignWorldTerrain-20261005/Local/art-r10-final/User/Saved/Screenshots/art-r10-final_overview.png'
blocks=[card('Native Mountain05 — 8.16 km authored domain',native,'Actual earlier UE capture, original orientation and different camera/lighting. Strong continuous ridges and basins. Not an ordinary-height matched comparison.'),card('Qualified retained Soul — 1.5 km',pairs[0][1],'Preserved reference: gameplay and settlements proven. Human/Mesa/waterfront derivatives contain rough regional edits.'),card('Bounded Mountain05 candidate — 3.5 km',pairs[1][1],'Same original height samples, 90° rotation and uniform XYZ compression. No flattening. Candidate uses provisional auto-slope surface and lowered water.'),card('Rejected R10 — historical comparison only',r10,'Smooth macro surfaces and artificial regional bands remain rejected. No R10 terrain or gameplay profile is activated.')]
page='''<!doctype html><html lang="en"><meta charset="utf-8"><title>SOUL terrain foundation evidence — 7 October 2026</title><style>
body{margin:0;background:#101820;color:#e8edf1;font:17px/1.5 system-ui}main{max-width:1500px;margin:auto;padding:32px}h1{font-size:32px}h2{margin-top:38px;font-size:24px}.notice{padding:20px;border-left:5px solid #e1ad59;background:#21313d}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}figure{margin:0;background:#1c2a35;border-radius:8px;overflow:hidden}img{display:block;width:100%;height:auto}figcaption{padding:14px}a{color:#acd8f6}table{border-collapse:collapse;width:100%;margin:20px 0}td,th{text-align:left;border-bottom:1px solid #425360;padding:10px}.small{color:#b4c3ce;font-size:14px}@media(max-width:850px){.grid{grid-template-columns:1fr}}</style><main>
<h1>SOUL: source and compressed-world scale evidence</h1>
<div class="notice"><b>Recommendation: 3.5 × 3.5 km as the next working footprint; do not promote this candidate.</b><br>Mountain05 is the strongest directly verified source. Its relief is useful and the capital has more countryside, but the candidate does not yet solve river crossings, six-region identity, surface quality or production roads. FreshCan still needs direct source inspection. The retained 1.5 km map remains the active qualified reference.</div>
<p>This is a separate editor study, not a new campaign authority. All 36 IDs and 51 legal edges remain unchanged. No donor, reference Landscape, save system, battle system or authored city was edited. Images below are actual Unreal captures; analytical diagrams are explicitly labelled.</p>
<h2>Source comparison</h2><div class="grid">'''+''.join(blocks)+'''</div>
<p><b>FreshCan FREE 4x4km Coastal Landscape Sample:</b> owned source was unavailable after bounded local/cache/download-path checks. <a href="https://www.fab.com/listings/fe1373c0-969d-4ebf-a8f0-9468fd29d239">Official listing</a>. Publisher imagery is not a measured heightfield or a GTX 1080 test. No local slope, drainage or performance numbers are claimed.</p>
<table><tr><th>Measurement</th><th>Native Mountain05</th><th>Retained Soul</th><th>FreshCan</th></tr><tr><td>Physical side</td><td>8.16 km</td><td>1.50 km</td><td>4 km listed; source unmeasured</td></tr><tr><td>Height range, relative to source water</td><td>−72.35 to 355.43 m</td><td>−13.30 to 65.33 m</td><td>Unknown</td></tr><tr><td>Land slope median / P95</td><td>17.17° / 31.79°</td><td>14.34° / 30.84°</td><td>Unknown</td></tr><tr><td>Land at ≤22°</td><td>70.71%</td><td>78.31%</td><td>Unknown</td></tr></table>
<p>The Human transplant’s affected-area median slope fell from 19.24° to 8.38°. That is a specific regional edit consequence; it does not mean all lowland must be steep. The new source study retains the original samples and finds a naturally gentler capital basin.</p>
<h2>3.5 km versus 4.0 km</h2><table><tr><th>Analytical layout</th><th>3.5 km</th><th>4.0 km</th></tr><tr><td>Total area</td><td>12.25 km²</td><td>16 km² (+31%)</td></tr><tr><td>Median nearest-region separation</td><td>375 m</td><td>448 m</td></tr><tr><td>Human capital nearest region</td><td>409 m</td><td>455 m</td></tr><tr><td>Measured Human core</td><td colspan="2">69.70 × 51.44 m, unchanged</td></tr><tr><td>Maximum coarse road detour ratio</td><td>3.80×</td><td>3.76×</td></tr></table>
<p>3.5 km provides adequate room for the measured scale objects. Extra area does not resolve shoreline/topology mismatches. These are layout proposals; several neighboring region nodes are route features rather than separate towns.</p>
'''+card('Matched scale comparison',LOCAL/'scale-comparison.jpg','Upper pair: matching normalized world framing. Lower pair: both 320 m camera distance, 42° pitch, −90° yaw, 52° FOV. Lighting and population differ; use this to judge scale, not claim equal art quality.')+'''
<h2>The water decision is still open</h2><p>The rendered road study lowered the native datum by 2.14 m. This exposes shallow connections: 28 existing study paths contain submerged portions if the original datum is restored. A new dry-route fit at that original datum finds only 38/51 paths under the same dense grade/bank rules. Thus 51 dry roads are <b>not</b> proof of a finished water/crossing design.</p><div class="grid">'''+card('Lowered water: provisional road study',LOCAL/'water-comparison/lower-datum.png','13.66% water coverage. Terrain heights unchanged. This shoreline is not approved.')+card('Original native water datum',LOCAL/'water-comparison/original-native-datum.png','18.08% water coverage. A connected inlet occupies much of the centre; this is not already the designed Heart River.')+card('Analytical shoreline sensitivity',OUT/'shoreline-sensitivity.png','Orange ground is exposed by the 2.14 m lower datum. Labels mark current proposed sites, not qualified crossings.')+card('Analytical crossing opportunities',OUT/'crossing-opportunities.png','Short bank-to-bank opportunities exist near Southern Crossing. River Ford and Broken Bridge would require substantial placement reconsideration; a sea-inlet bridge is not automatically a river ford.')+'''</div>
<h2>All twelve candidate views</h2><p>1920 × 1080 editor captures at a 12 FPS review cap. No uncapped performance claim. Surface, water and woodland remain provisional; only Human/Dwarf and representative minor/army scale objects are placed.</p><div class="grid">'''+''.join(card(c,CAP/(n+'.png'),'Click for the original full-resolution screenshot.') for n,c in views)+'''</div>
<h2>Acceptance</h2><ul><li>Proven: every sample of the surviving 2041² full-domain source export preserved; 3.5 km envelope; exact 36/51 identity sets; native collision sampling; saved 64-component map; existing mesh scales; fresh editor reload. This is not a copy of all 8161² native vertices.</li><li>Provisional: all road art, static settlement placement, auto-slope surface, woodland distribution and water datum.</li><li>Known defects: Viking harbor faces an enclosed lake; River Ford is not a river crossing; original-water dry connectivity incomplete; some road shoulders reach 26.11°; roads stop short of settlement gates; abrupt square terrain boundary; weak forest masses and missing faction-specific terrain treatments.</li><li>Not implemented: production campaign binding/travel through this map, canonical river system, final regional biomes, full population, production performance qualification.</li></ul><p>Twenty additional analytical source framings (five 6.12 km windows × four rotations, all at 3.5 km physical scale and original water) find only 39–45 of 51 coarse dry paths. None improves on the full-domain 46/51 coarse result. The best route-count crop gives poor Dwarf/Viking roles. No additional landscape was imported; cropping is not a demonstrated cure.</p><p><b>Next action:</b> inspect the exact FreshCan source when accessible, then resolve the coast/river/crossing composition on a 3.5 km plan before any more terrain authoring or campaign promotion. Keep Mountain05’s authored relief as the verified fallback and preserve the current reference map.</p>
<p class="small">Detailed receipts: <a href="HANDOFF.md">HANDOFF</a> · <a href="fresh-editor-validation.json">fresh editor validation</a> · <a href="source-scale-decision.md">source/scale decision</a>. Full local evidence and licensed-derived assets remain on this worker; nothing is pushed.</p></main></html>'''
(OUT/'visual-review.html').write_text(page,encoding='utf-8')
manifest=[]
for _,p in pairs:
 manifest.append({'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
(OUT/'comparison-image-manifest.json').write_text(json.dumps(manifest,indent=2));print(OUT/'visual-review.html')
