"""Deterministic damage cuts in owned bridge visuals; original collision retained."""
import unreal as u,json,math
from pathlib import Path
R=Path('D:/RefinedBadger/Worktrees/Soul-bannerlord-campaign-map-20260929');E=R/'Evidence/DwarfPassGate-20261007';root='/Game/SoulCampaignComposition/PassGatePolish';actors=u.get_editor_subsystem(u.EditorActorSubsystem);rows=[]
w=u.get_editor_subsystem(u.UnrealEditorSubsystem).get_editor_world();assert w.get_path_name().startswith('/Game/SoulCampaignComposition/L_Composition_3500_r2')
for side,cutx,flip,yaw,notches in [('West',-1392,True,11,[(-1460,5,165,155,135),(-1650,-585,125,145,110)]),('East',-618,False,-8,[(-550,-585,200,155,170),(-405,5,110,150,100)])]:
 ac=next(a for a in actors.get_all_level_actors() if a.get_actor_label()=='Polish_Crossing_broken_'+side);source=ac.static_mesh_component.static_mesh;materials,names=u.GeometryScript_AssetUtils.get_material_list_from_static_mesh(source);mesh=u.DynamicMesh();opt=u.GeometryScriptCopyMeshFromAssetOptions();opt.apply_build_settings=False;opt.use_build_scale=False;lod=u.GeometryScriptMeshReadLOD();lod.lod_type=u.GeometryScriptLODType.RENDER_DATA;lod.lod_index=0
 _,ok=u.GeometryScript_AssetUtils.copy_mesh_from_static_mesh_v2(source,mesh,opt,lod,False);assert ok==u.GeometryScriptOutcomePins.SUCCESS
 before=mesh.get_triangle_count();frame=u.Transform();frame.translation=u.Vector(cutx,-294,-100);frame.rotation=u.Rotator(pitch=90,yaw=yaw).quaternion();cut=u.GeometryScriptMeshPlaneCutOptions();cut.fill_holes=True;cut.fill_spans=True;cut.flip_cut_side=flip;cut.hole_fill_material_id=0;u.GeometryScript_MeshBooleans.apply_mesh_plane_cut(mesh,frame,cut)
 for i,(x,y,sx,sy,sz) in enumerate(notches):
  tool=u.DynamicMesh();tr=u.Transform();tr.translation=u.Vector(x,y,80-sz/2);tr.rotation=u.Rotator(pitch=(i+1)*12,yaw=17+i*13,roll=9).quaternion();u.GeometryScript_Primitives.append_box(tool,u.GeometryScriptPrimitiveOptions(),tr,sx,sy,sz,origin=u.GeometryScriptPrimitiveOriginMode.CENTER)
  u.GeometryScript_MeshBooleans.apply_mesh_boolean(mesh,u.Transform(),tool,u.Transform(),u.GeometryScriptBooleanOperation.SUBTRACT,u.GeometryScriptMeshBooleanOptions())
 package=root+'/SM_BrokenBridge_'+side+'_r1';assert not u.EditorAssetLibrary.does_asset_exist(package);create=u.GeometryScriptCreateNewStaticMeshAssetOptions();create.enable_nanite=False;create.enable_collision=False;asset,ok=u.GeometryScript_NewAssetUtils.create_new_static_mesh_asset_from_mesh(mesh,package,create);assert ok==u.GeometryScriptOutcomePins.SUCCESS;asset.static_materials=[u.StaticMaterial(material_interface=m,material_slot_name=n) for m,n in zip(materials,names)];assert u.EditorAssetLibrary.save_loaded_asset(asset)
 visual=actors.spawn_actor_from_class(u.StaticMeshActor,ac.get_actor_location(),ac.get_actor_rotation());visual.set_actor_scale3d(ac.get_actor_scale3d());visual.static_mesh_component.set_static_mesh(asset);visual.set_actor_label('PassGate_BrokenVisual_'+side);visual.set_actor_enable_collision(False)
 # Rendering-only replacement: inherited collision shape stays byte-identical.
 ac.static_mesh_component.set_visibility(False);ac.static_mesh_component.set_cast_shadow(False)
 rows.append(dict(side=side,source=source.get_path_name(),visual=asset.get_path_name(),before_triangles=before,after_triangles=mesh.get_triangle_count(),collision_actor=ac.get_actor_label(),cut_local_x_cm=cutx,cut_yaw_deg=yaw,notches=notches))
assert u.get_editor_subsystem(u.LevelEditorSubsystem).save_current_level();(E/'broken-bridge-damage-r1.json').write_text(json.dumps(dict(method='Angled fracture cuts plus asymmetric parapet notches of owned stone bridge; native materials retained; no generated art.',collision_unchanged=True,timber_unchanged=True,terrain_changed=False,derivatives=rows),indent=2));print('BROKEN_VISUALS',rows)
