"""Build the local review from archived runtime evidence; never invent pass results."""
from pathlib import Path
import json,html,shutil
P=Path('D:/RefinedBadger/AssetLibraries/SoulTerrainPreview')
R=P/'SoulIntegration/EvilCorridor'
cards=[('Crownstead and the western road','evil-input-03','evil-input-03_initial.png'),('Travel across the shared stone bridge','evil-victory-03','Corridor_Bridge_Travel.png'),('Ashport after conquest and return travel','evil-victory-03','Corridor_Ashport_Return.png'),('Cinder Crown: corrected edge focus','evil-victory-03','Campaign_Stronghold.png'),('Physical Dragon Graveyard battle','evil-victory-03','Vertical_Battle.png'),('Defeat returns to the campaign','evil-defeat-01','Vertical_Campaign_Return.png')]
receipts={run:json.loads((R/run/'receipt.json').read_text()) for run in {r for _,r,_ in cards}}
for r in receipts.values():
 assert r['runtime']['exit_code']==0 and r['runtime']['completion_marker_observed']
shutil.copy2(Path(__file__).resolve().parents[1]/'Evidence/CampaignWorld/before-1280.png',R/'original-graph.png')
sections=['<details><summary>Original campaign graph, before the terrain lane</summary><img src="SoulIntegration/EvilCorridor/original-graph.png" alt="Archived original campaign graph"><p>Archived baseline from the earlier campaign-world pass; the current corridor builds on that work.</p></details>']
for title,run,name in cards:
 p=R/run/name;assert p.exists(),p
 sections.append(f'<section><h2>{html.escape(title)}</h2><a href="SoulIntegration/EvilCorridor/{run}/{name}"><img src="SoulIntegration/EvilCorridor/{run}/{name}" alt="{html.escape(title)}" loading="lazy"></a><p>Unreal runtime · 1280 × 720 · <a href="SoulIntegration/EvilCorridor/{run}/receipt.json">run receipt</a></p></section>')
peak=max(r['peak_gpu_temperature_c'] for r in receipts.values())
head='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Soul · playable western corridor</title><style>body{margin:0;background:#121b20;color:#e7e5db;font:17px/1.6 system-ui}main{max-width:1280px;margin:auto;padding:30px}h1{font-size:38px;line-height:1.2}h2{font-size:23px}p{max-width:950px}a{color:#d5bd84}section{margin:36px 0;background:#1d2b31;padding:20px;border-radius:8px}img{width:100%;height:auto;display:block}code{overflow-wrap:anywhere}small{color:#bdc8c9}.tag{color:#b7d9b2}</style><main><a href="settlement-plan.html">Settlement proposal</a> · <a href="terrain-comparison.html">Terrain comparison</a><h1>Crownstead → Bridgeward → Ashport</h1><p class="tag">Playable local corridor candidate · existing nine-region campaign authority</p><p>The western route now crosses a stone bridge, follows the shore, and reaches the evil waterfront. Ashport can be conquered through a physical Dragon Graveyard battle; ownership, survivors and action points are verified on return.</p><p>Run <code>Tools/Open_Soul_Evil_Corridor.bat</code> in the Soul worker. This uses a separate player save profile. WASD pan, wheel zoom, middle-mouse drag, Q/E orbit, Home focus, T town, B battle, F5/F9 save/load.</p>'''
tail=f'''<section><h2>What this proves—and what remains</h2><p>The pictured runs completed normally. Peak GPU temperature across these runs: {peak:g}°C at 720p / 30 FPS. The bridge and fortress views were inspected after capture.</p><p>This is an editor-game candidate, not an updated packaged RC2. The settlement proposal's other faction cities are still planning. Buildings, road materials, the pier and terrain dressing remain prototype art. Physical OS input and a full-map balance pass remain unqualified.</p><p>The corridor preserves the existing terrain heightfield. Its mountain routes include short grades up to 27.9°; the previous plains profile is unchanged.</p></section></main></html>'''
(P/'evil-corridor.html').write_text(head+''.join(sections)+tail,encoding='utf-8')
print(P/'evil-corridor.html')
