from pathlib import Path
import json
r=Path(__file__).resolve().parents[1];data=json.loads((r/'TerrainWork/settlement-plan.json').read_text())
html="""<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Soul • Settlement proposal</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#131a18;color:#efe9da;font:16px system-ui}header{padding:22px 30px 12px}h1{font:34px Georgia;margin:5px 0 10px}p{line-height:1.5;color:#c0c8be;max-width:1000px}a{color:#e5c482}button{font:inherit;border:1px solid #617365;border-radius:5px;background:#202d26;color:#ebe8dc;padding:8px 12px;cursor:pointer}button[aria-pressed=true]{background:#dcc18b;color:#17221b}.filters{display:flex;gap:8px;flex-wrap:wrap;margin:15px 0}.layout{display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:18px;padding:0 30px 25px;max-width:1800px;margin:auto}svg{width:100%;height:auto;display:block;background:#0b100d}aside{background:#1c2821;padding:20px;align-self:start}h2{font:26px Georgia;margin:0 0 10px}h3{font-size:16px}.list{display:grid;gap:7px;margin:15px 0}.list button{text-align:left}.mapmark{cursor:pointer}.mapmark:focus{outline:none}.mapmark:focus circle,.mapmark:hover circle{stroke:white;stroke-width:4}.label{fill:#fff5df;font:16px system-ui;paint-order:stroke;stroke:#152019;stroke-width:5;stroke-linejoin:round;pointer-events:none}.capital-label{font-size:19px}.legend{font-size:14px;color:#c7cbbb;display:flex;gap:20px;margin:10px 0}.detail{font-size:14px}.route{fill:none;stroke:#ecd19d;stroke-width:2.2;opacity:.85;pointer-events:none}footer{padding:10px 30px 30px}footer a{margin-right:18px}.notice{border-left:3px solid #b09a6d;padding-left:12px}.views{display:grid;grid-template-columns:1fr 1fr;gap:16px;padding:0 30px}.views img{width:100%}@media(max-width:950px){.layout{grid-template-columns:1fr;padding:0 12px}.views{grid-template-columns:1fr}.list{grid-template-columns:repeat(3,1fr)}aside{padding:15px}}
</style>
<header><a href="mesa-transplant.html">Previous mesa comparison</a><h1>Six realms · Capital and city proposal</h1><p>The evil region now reaches the north bank. These are recommended settlement sites, with placeholder names, selected for terrain, access and strategic role. Cities, faction ownership and naval travel have not been implemented by this plan.</p><div class="filters" id="filters"></div></header>
<div class="layout"><main><svg id="map" viewBox="430 0 1060 1080" role="img" aria-label="Terrain map with eighteen proposed settlements"><image href="TerrainWork/Captures/L_evil_waterfront_overhead.png" width="1920" height="1080"/><g id="routes"></g><g id="marks"></g></svg><div class="legend"><span>★ Capital</span><span>◆ Port</span><span>● City / stronghold</span></div><label><input type="checkbox" id="showroutes" checked> Show sampled land approaches for selected faction</label><p class="detail">Route lines are terrain checks below 22° within the proposed faction area, not built roads or in-game pathfinding. Missing routes are flagged for pass work.</p></main><aside><div id="details" aria-live="polite"></div><div class="list" id="sites"></div><p class="detail notice">Recommendation: begin with these 18 major places. Add villages around farms, mines and forests after travel times and city spacing are tested. Keep capitals distinct from frontier forts.</p></aside></div>
<div class="views"><section><h2>Evil waterfront</h2><a href="TerrainWork/Captures/L_evil_waterfront_evil_harbor.png"><img src="TerrainWork/Captures/L_evil_waterfront_evil_harbor.png" alt="Volcanic terrain extending to the shore"></a></section><section><h2>Whole-world campaign view</h2><a href="TerrainWork/Captures/L_evil_waterfront_campaign.png"><img src="TerrainWork/Captures/L_evil_waterfront_campaign.png" alt="Whole map with new coastal evil region"></a></section></div>
<footer><p>Design references: settlement roles and defended provinces from Total War; productive hinterlands, trade access and route control from Bannerlord. The actual placements and names here are our proposal, not copied locations.</p><div id="sources"></div></footer>
<script>
const DATA=__DATA__,colors={Humans:'#e8c767',Dwarves:'#a4bfd0',Nature:'#82dca1',Orcs:'#d9a46a',Vikings:'#7ed5eb',Evil:'#f08d79'};
let faction='Evil',selected='E2';const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
function svg(tag,attrs,parent){let e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));parent.append(e);return e}
function choose(id){selected=id;faction=DATA.sites.find(s=>s.id===id).faction;render()}
function render(){
 $('filters').innerHTML='';['All',...Object.keys(colors)].forEach(f=>{let b=document.createElement('button');b.textContent=f;b.setAttribute('aria-pressed',f===faction);b.onclick=()=>{faction=f;if(f!=='All')selected=DATA.sites.find(s=>s.faction===f).id;render()};$('filters').append(b)});
 $('routes').innerHTML='';if($('showroutes').checked&&faction!=='All')DATA.routes.filter(r=>r.faction===faction&&r.pass).forEach(r=>svg('polyline',{points:r.points.map(p=>p.join(',')).join(' '),class:'route'},$('routes')));
 $('marks').innerHTML='';
 DATA.sites.forEach(s=>{let active=faction==='All'||s.faction===faction,chosen=s.id===selected;let [x,y]=s.screen,g=svg('g',{class:'mapmark',transform:'translate('+x+' '+y+')',opacity:active?1:.45,tabindex:0,role:'button','aria-label':s.faction+' '+s.kind+': '+s.name},$('marks'));g.onclick=()=>choose(s.id);g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(s.id)}};
 svg('circle',{r:chosen?16:12,fill:'#14201a',stroke:colors[s.faction],'stroke-width':chosen?4:2},g);let icon=svg('text',{'text-anchor':'middle',y:6,fill:colors[s.faction],'font-size':19},g);icon.textContent=s.kind==='capital'?'★':s.kind==='port'?'◆':'●';
 let right=x<1370,t=svg('text',{x:right?19:-19,y:5,'text-anchor':right?'start':'end',class:'label'+(s.kind==='capital'?' capital-label':'')},g);t.textContent=s.id+(active&&s.kind==='capital'?' '+s.name:'');
 });
"""
html+="""
 const s=DATA.sites.find(s=>s.id===selected),rs=DATA.routes.filter(r=>r.to===s.id||r.from===s.id),ok=rs.every(r=>r.pass);
 $('details').innerHTML='<div style="color:'+colors[s.faction]+'">'+s.faction+' · '+s.kind+'</div><h2>'+s.name+'</h2><p>'+s.why+'</p><p class="detail">'+s.caution+'</p><h3>Terrain check</h3><p class="detail">Local slope '+s.slope_deg.toFixed(1)+'° · sampled 24 m footprint relief '+s.footprint_relief_m.toFixed(1)+' m.<br>'+(s.kind==='port'?'Approx. '+s.shore_distance_m_approx.toFixed(0)+' m from water.<br>':'')+(s.earthworks?'Terracing / foundation work recommended.<br>':'')+(ok?'Sampled connections to faction cities found.':'One or more connections need a designed pass; placement is conditional.')+'</p>';
 $('sites').innerHTML='';DATA.sites.filter(s=>faction==='All'||s.faction===faction).forEach(s=>{let b=document.createElement('button');b.textContent=s.id+' · '+s.name;b.setAttribute('aria-pressed',s.id===selected);b.onclick=()=>choose(s.id);$('sites').append(b)});
}
$('showroutes').onchange=render;
DATA.sources.forEach(s=>{let a=document.createElement('a');a.href=s.url;a.target='_blank';a.rel='noopener';a.textContent=s.title;$('sources').append(a)});
render();
</script></html>"""
(r/'settlement-plan.html').write_text(html.replace('__DATA__',json.dumps(data)),encoding='utf-8');print('Built settlement-plan.html')
