from pathlib import Path
import json,struct
r=Path(__file__).resolve().parents[1]
views=['human_plains','overhead','campaign','dwarf_foothills','northern_lake']
for v in views:
    p=r/'TerrainWork/Captures'/('L_grass_coast_v2_'+v+'.png')
    assert struct.unpack('>II',p.read_bytes()[16:24])==(1920,1080)
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Soul â€¢ Grassland transplant</title>
<style>body{margin:0;background:#141915;color:#ebe9dd;font:16px system-ui}header,main{max-width:1500px;margin:auto;padding:24px}h1{font:38px Georgia;margin:8px 0}p{max-width:920px;line-height:1.6;color:#bbbfb5}.controls{display:flex;gap:20px;align-items:center;flex-wrap:wrap;margin:20px 0}select,button{font:inherit;padding:10px;background:#29352c;color:#f0ebde;border:1px solid #63705b;border-radius:6px}.compare{position:relative;aspect-ratio:16/9;background:#000;overflow:hidden}.compare img{position:absolute;width:100%;height:100%;object-fit:contain}.after{clip-path:inset(0 50% 0 0)}.split{position:absolute;top:0;bottom:0;left:50%;width:2px;background:#e2c887;pointer-events:none}.labels{display:flex;justify-content:space-between;color:#e2c887}input{width:100%;margin:20px 0}section{margin:32px 0}section img{width:100%;display:block}a{color:#ddc68b}.notes{padding:18px;background:#202920;border-left:3px solid #b2a77b}</style>
<header><a href="terrain-comparison.html">All terrain candidates</a><h1>Mountain 05 Â· Human heartland</h1><p>One continuous 1.5 Ã— 1.5 km Landscape. Grassland 02 hills replace the enclosed plains and extend to the north and west shoreline. Eastern and southern mountains, the northern lake and the water footprint remain.</p><p>Actual Unreal screenshots. Terrain study only: campaign locations, recruitment and battles are not integrated into this map yet.</p></header><main>
<div class="controls"><label>Comparison <select id="view"><option value="human_plains">Human plains Â· campaign angle</option><option value="overhead">Entire map Â· overhead</option></select></label><button id="toggle">Toggle before / after</button><a id="full" target="_blank">Open after at full size</a></div>
<div class="labels"><span>AFTER Â· rolling plains</span><span>BEFORE Â· original ridges</span></div><div class="compare"><img id="before" alt="Before terrain edit"><img id="after" class="after" alt="After terrain edit"><div class="split"></div></div><label>Drag to compare<input id="slider" aria-label="Before after split" type="range" min="0" max="100" value="50"></label>
<div class="notes">The human region now extends to the coast; donor hills blend into the remaining mountain belt. Terrain routes to the coast and mountain foothills pass a 22Â° slope threshold; a land route around the northern lake also passes. These are sampled terrain checks, not in-game movement qualification. The original licensed map is unchanged.</div>
'''
for v in ['campaign','dwarf_foothills','northern_lake']:
    src='TerrainWork/Captures/L_grass_coast_v2_'+v+'.png'
    html+=f'<section><h2>{v.replace("_"," ").title()}</h2><a href="{src}" target="_blank"><img loading="lazy" src="{src}" alt="{v}"></a></section>'
html+='''<script>const view=document.querySelector('#view'),slider=document.querySelector('#slider');function split(){document.querySelector('#after').style.clipPath=`inset(0 ${100-slider.value}% 0 0)`;document.querySelector('.split').style.left=slider.value+'%'}function update(){document.querySelector('#before').src='TerrainWork/Captures/L_mountain_campaign_'+view.value+'.png';document.querySelector('#after').src='TerrainWork/Captures/L_grass_coast_v2_'+view.value+'.png';document.querySelector('#full').href=document.querySelector('#after').src}view.onchange=update;slider.oninput=split;document.querySelector('#toggle').onclick=()=>{slider.value=slider.value<50?100:0;split()};update();split();</script></main></html>'''
(r/'grassland-transplant.html').write_text(html,encoding='utf-8');print('Built grassland-transplant.html')
