"""Derive a non-runtime six-faction readiness manifest from existing canonical data."""
from pathlib import Path
import json,hashlib,argparse
R=Path(__file__).resolve().parents[2];E=R/'Evidence/ProductionContinuation-20261008'
p=argparse.ArgumentParser();p.add_argument('--evidence-root',type=Path,required=True);p.add_argument('--matchup-receipt',type=Path,required=True);a=p.parse_args();E=a.evidence_root.resolve();assert E.is_relative_to((R/'Evidence').resolve())
proof=json.loads(a.matchup_receipt.read_text());assert proof['pass'] and proof['faction']=='orcs' and proof['unit']=='orc_hammer_warrior'
src=R/'Data/soul_campaign_start_states_v1_20260922.json';geo=R/'Data/soul_world_overmap_v1_20260922.json';s=json.loads(src.read_text())['scenarios']['six_faction_sandbox_candidate'];g=json.loads(geo.read_text());p=json.loads((R/'Data/CampaignComposition/presentation.json').read_text());ids={n['id'] for n in g['nodes']};edges={frozenset([e['a'],e['b']]) for e in g['edges']}
assert len(ids)==36 and len(edges)==51 and set(s['factions'])=={'humans','vikings','dwarves','orcs','nature','dark'}
assert set(s['region_owners'])|set(s['neutral_regions'])==ids
assert not set(s['region_owners'])&set(s['neutral_regions'])
rows=[]
for faction,f in s['factions'].items():
 for field in ['capital_region','secondary_settlement_region']:assert f[field] in ids and f[field] in p['regions']
 for rid in f['starting_possessions']:assert s['region_owners'][rid]==faction
 frontier=set(f['immediate_neutral_frontier_candidates']);assert frontier<=ids
 for v in f['army_spawn_anchors']:assert v['region_id'] in ids
 rows.append({'faction':faction,'capital_region':f['capital_region'],'secondary_region':f['secondary_settlement_region'],'physical_capital_cm':p['regions'][f['capital_region']],'canonical_starting_possessions':f['starting_possessions'],'canonical_neutral_frontier':sorted(frontier),'army_profile':f['starting_army']['profile'],'environment_role_authority':'Evidence/SettlementEnvironmentPlan-20261005/faction-role-matrix.md','runtime_enabled':False,'exact_qualified_unit_ids':{'humans':['human_knight'],'dwarves':['dwarf_warrior'],'orcs':['orc_hammer_warrior']}.get(faction,[]),'seven_family_roster_qualified':False})
adj={n['id']:set() for n in g['nodes']}
for edge in g['edges']:adj[edge['a']].add(edge['b']);adj[edge['b']].add(edge['a'])
for row in rows:
 owned=set(row['canonical_starting_possessions']);direct=set().union(*(adj[n] for n in owned))-owned
 row['actual_adjacent_frontier_ids']=sorted(direct)
 row['declared_frontier_not_immediately_adjacent']=sorted(set(row['canonical_neutral_frontier'])-direct)
 row['capital_secondary_legal_connection']=row['secondary_region'] in adj[row['capital_region']]
 assert not row['declared_frontier_not_immediately_adjacent'],row['faction']
blockers=[{'area':'save validation','current':'accepts player/enemy/neutral only','required':'Explicit admitted faction set and adversarial restore tests; retain RBSave domains.'},{'area':'battle roster binding','current':'one PlayerUnitId/EnemyUnitId pair per encounter; exact Humans/human_knight versus Dwarves/dwarf_warrior or Orcs/orc_hammer_warrior admitted; Orc proof fields one hammer infantry unit, not a complete faction roster','required':'Admit reviewed roster/presentation bindings through the existing descriptor and Combat bridge; keep rejection of unsupported matchups until each binding is qualified. Do not merely remove the whitelist or cosmetically relabel a faction.'},{'area':'army state and AI','current':'static founder garrisons; no multi-faction strategic army controller','required':'Use existing SoulCore commander/army rules with explicit deterministic scheduling.'},{'area':'recruitment and settlement development','current':'Human capital roster and one active development scenario','required':'Admitted faction definitions and existing state authority bindings; no six-city proof project.'},{'area':'balance and diplomacy','current':'canonical sandbox candidate still marks starting army balance pending','required':'Product approval of starting forces/diplomacy before activation.'},{'area':'save compatibility','current':'composition uses isolated slots; 9-region shapes rejected by existing validator','required':'No implicit migration. A future reviewed migration must preserve old slot and both save domains.'}]
out={'schema':2,'qualified_new_matchup_receipt':str(a.matchup_receipt.resolve().relative_to(R)),'qualified_new_matchup_receipt_sha256':hashlib.sha256(a.matchup_receipt.read_bytes()).hexdigest(),'status':'CONFIGURATION_GROUNDWORK_NOT_RUNTIME_SCENARIO','canonical_start_source':str(src.relative_to(R)),'canonical_start_sha256':hashlib.sha256(src.read_bytes()).hexdigest(),'geography_source':str(geo.relative_to(R)),'geography_sha256':hashlib.sha256(geo.read_bytes()).hexdigest(),'regions':36,'legal_pairs':51,'factions':rows,'owned_start_regions':len(s['region_owners']),'neutral_start_regions':len(s['neutral_regions']),'blockers':blockers,'new_gameplay_authority':False,'runtime_fixture_ownership_changed':False,'runtime_identity_gate':{'source':'Source/SoulCore/Private/SoulCampaignBattleBridge.cpp','player_faction':'humans','player_unit':'human_knight','ordered_enemy_pairs':[{'faction':'dwarves','unit':'dwarf_warrior','scope':'existing qualified bridge; inherited multi-role visual presentation remains unchanged'},{'faction':'orcs','unit':'orc_hammer_warrior','scope':'exact native hammer infantry, initial and reserves; cooked natural result, return and fresh load'}],'qualified_six_faction_roster_definitions':False},'configuration_contract':{'runtime_activation':False,'starting_forces':'BALANCE_LAB_OWNED_PENDING','diplomacy':'UNSET','required_roster_shape':{'total':7,'fighters':4,'ranged':1,'support_magic':1,'apex':1,'quadruped_body_plans':1,'heroes_separate':True},'shape_authority':'Source/SoulCore/Private/SoulFaction.cpp'},'implementation_sources':{n:hashlib.sha256((R/n).read_bytes()).hexdigest() for n in ['Source/SoulCore/Private/SoulCampaignBattleBridge.cpp','Source/SoulCore/Private/SoulFaction.cpp','Source/Soul/Private/SoulFounderPlaytestStateSubsystem.cpp']}}
(E/'six-faction-readiness.json').write_text(json.dumps(out,indent=2));print('SIX_FACTION_GROUNDWORK_VALID',len(rows),len(ids),len(edges))
